# Deployed with:
# gcloud run deploy b6build-nightly-notifier \
#   --region=europe-west1 \
#   --image=us-east1-docker.pkg.dev/gcb-release/cloud-build-notifiers/slack:latest \
#   --no-allow-unauthenticated \
#   --update-env-vars=CONFIG_PATH=gs://diagonal.works/etc/b6build-nightly-notifier.yaml,PROJECT_ID=diagonal-platform
apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: b6build-nightly-notifier
spec:
  notification:
    filter: build.status == Build.Status.SUCCESS
    params:
      buildStatus: $(build.status)
    delivery:
      webhookUrl:
        secretRef: webhook-url
    template:
      type: golang
      uri: gs://diagonal.works/etc/b6build-nightly-template.json
  secrets:
  - name: webhook-url
    value: projects/854624783986/secrets/slack-b6build-webhook/versions/1

